#:kivy 2.2.1

<SettingsScreen>:

    PressedButton:
        text: "Passer en français"
        size_hint: (0.5, 0.1)
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        font_ratio: root.font_ratio
        release_function: root.change_language

    PressedSpinner:
        text: "Passer en français"
        values:["A","B","C","D","E","F","G","H","I","J"]
        size_hint: (0.5, 0.1)
        pos_hint: {"center_x": 0.5, "center_y": 0.3}
        font_ratio: root.font_ratio